schema_version = "1.0.0"
id = "mouselook_navigation"
version = "1.9.6"
name = "Mouselook Navigation"
tagline = "Provides extra 3D view navigation options (ZBrush mode) and customizability"
maintainer = "dairin0d, moth3r"
type = "add-on"


# Optional link to documentation, support, source files, etc
website = "https://docs.moth3r.com"


tags = ["3D View"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]
